version: '3.4'
services:
  notebook:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/FENS-2022
      - ./notebooks:/content
      - ./data:/content/data
      - ./trained_nets:/content/trained_nets
    environment:
    - GIT_SSL_NO_VERIFY=1
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
